### ISSUE TITLE
Wiki: output report 

### ISSUE THREAD

**Issue by dvarrui** [teuton-software/teuton#28]
Explain output report information.

**Comment by JuanMoroteP** [comment]
Hi,

First of all congratulations!!! It's really a great and useful tool that I'm going to use with my students. 

It would be great to have the option to choose what to include in the results report. At least in the report to be send to the targets in order to inform the students about their results.

Sometimes the command that the teacher uses to check if the target is reached includes the solution to the proposed task, so the student only should take a look into the report to fullfill the proposed tasks.

So a solution could be to provide two different reports. One option by default with all the information, and a short report with only "Description", "Duration" and "Result" fields excluding "command", "alterations" and "expected" fields.

    02 (1.0/1.0)
        Description : Servicio vsftpd instalado
        Command     : **apt list vsftpd**
        Duration    : 0.742 (ssh)
        Alterations : find(installed) & count
        Expected    : Greater than 0 (String)
        Result      : 1 (Integer)

Thanks
Juan

**Comment by dvarrui** [comment]
Thank you!

For example "export" sentence will export reports with all fields and "export verbose: false" will export reports excluding some fields (command, alterations and expected).

do you like this solution?

**Comment by JuanMoroteP** [comment]
That sounds great!!!!
Many thanks,

**Comment by dvarrui** [comment]
We are thinking of these solutions:

1) export hide: ["Command", "Duration", "Alterations", "Expected", "Result"]
2) export show: ["Description"]
3) export verbose: false (only description will be showed)
4) export format: :list 

Using 1, 2, 3... output reports will show hidden fields empty but with 4 option there will be another report type that only will show description field.

**Comment by dvarrui** [comment]
Install teuton version 2.4.0 (gem install teuton) or update (gem update teuton)

Disable feedback when exporting reports.
```
export format: "html", feedback: false
```

Feedback information only affects to "command", "alterations", "expected" and "result" field (Example: https://github.com/teuton-software/teuton/blob/master/examples/17-hide-feedback/start.rb)
